[package]
name = "ourobox"
version = "0.1.0"
edition = "2021"
description = "Ouroboros Box"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.53"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
sled = "0.34.7"
tokio = { version = "1.15.0", features = ["full"] }
